services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: motviet
    restart: always
    volumes:
      - ./:/app
    networks:
      - db_default
  nginx:
    image: nginx
    restart: always
    ports:
      - 9999:80
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./:/app
      - ./nginx_default.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - db_default
volumes:
 app_data:
networks:
  db_default:
    external: true
